-- message_feedback.feedback_reason (category / orchestrator enum)
-- Allowed values (do not store thumbs_up / thumbs_down here):
--   biased, incomplete_instructions, not_factual, not_relevant, other, style_tone, unsafe
--
-- Thumbs rating lives in metadata.rating (no separate rating column).
--
-- Thumbs up:
--   feedback=1, feedback_reason=NULL, preference_score=5, metadata={"rating":"thumbs_up"}
-- Thumbs down + reason:
--   feedback=-1, feedback_reason=not_factual, preference_score=1,
--   metadata={"rating":"thumbs_down"}, feedback_comment=...
